-- TrueMoan v1.8 by illa3d
-------------------------------------------------------------------------------------------------
-- MENU CLOTHES
-------------------------------------------------------------------------------------------------
TM_Clothes_Custom = {
	"2b",
	"ada wong",
	"aerith",
	"ahri kda",
	"akali",
	"android 18",
	"ashley",
	"aunt cass",
	"bayonetta",
	"black cat",
	"black male",
	"cammy",
	"cheri nowlin",
	"chunli",
	"cindy aurum",
	"ciri",
	"cloud",
	"dante",
	"dimitrescu",
	"dva",
	"elizabethbas",
	"elizabethyoung",
	"ellie",
	"emilie de rochefort",
	"eva",
	"eve",
	"eve_xmas",
	"faye valentine",
	"gemma",
	"generic male",
	"geralt",
	"hailey",
	"harley quinn",
	"honoka",
	"ifalna",
	"invisible woman",
	"irelia",
	"ivy",
	"jessie rasberry",
	"jill valentine",
	"jinx",
	"judy alvarez",
	"juliet",
	"juri sf6",
	"juri",
	"kitana",
	"lara croft",
	"leon s kennedy",
	"lily artemis",
	"link warriors",
	"loba",
	"lunafreya",
	"maddie",
	"mai shiranui",
	"marie rose",
	"mercy",
	"miss fortune",
	"morrigan",
	"mrx",
	"nyotengu",
	"panam",
	"pharah",
	"power",
	"primrose office",
	"primrose",
	"queen",
	"quiet",
	"rangiku",
	"raven teentitan",
	"raven",
	"samus",
	"scarlet",
	"shadowheart",
	"succubus",
	"tachy",
	"tifa lifeguard",
	"tifa",
	"tifa_kimono",
	"tracer",
	"triss",
	"ultimate bunny",
	"widowmaker",
	"witch mercy",
	"y'shtola",
	"yennefer",
	"yuffie",
	"zelda",
}