-- TrueMoan v1.7 by illa3d
--------------------------------------------------------------------------------------------------------------
-- TRUEFACE PRESETS (displayed in TalkMenu/Face)
--------------------------------------------------------------------------------------------------------------
TMMenuTag_TrueFace = "|tf| "

-- hack to load preset as a string instead of variable, fuck you custom menu piece of shit
-- spent 2 hours on this fucking retarded shit why do I even do this - illa3d
-- function TMStartFacePreset(human, preset) TrueFaceStart(human, preset) end
function TMMenu_TrueFacePreset(human, preset) TrueFaceStart(human, _G[preset]) end
TMMenuItems_TrueFace = {
	{ name = "Moan|max", preset = "TFPreset_MoanMax" },
	{ name = "Moan|high", preset = "TFPreset_MoanHigh" },
	{ name = "Moan|medium", preset = "TFPreset_MoanMedium" },
	{ name = "Moan|normal", preset = "TFPreset_MoanNormal" },
	{ name = "Moan|min", preset = "TFPreset_MoanMin" },
}

TFPreset_MoanMin = {
	updateRate = 0.06,
	mouthSpeed = 0.8,
	faceSpeed = 0.5,
	browSpeed = 0.6,
	auxSpeed = 0.4,
	intensityCurve = 0.9,
	jawBase = -0.15,
	jawWave = 0.05,
	jawPeak = 0.05,
	smileBase = 0.05,
	smileFreq = 0.3,
	smileWave = 0.1,
	smilePeak = 0.05,
	cheekFromSmile = 0.4,
	cheekPeak = 0.05,
	upperLipFreq = 0.4,
	upperLipMax = 0.1,
	upperLipPeak = 0.05,
	lowerLipFreq = 0.5,
	lowerLipMax = 0.1,
	lowerLipPress = 0.05,
	innerJawFreq = 0.3,
	innerJawWave = 0.05,
	innerJawPeak = 0.05,
	browInnerLift = 0.1,
	browInnerPeak = 0.05,
	browOuterFreq = 0.3,
	browOuterPress = 0.05,
	browOuterPeak = 0.05,
	browAsymFreq = 0.3,
	browAsym = 0.03,
	lipPhaseOffset = 0.1,
	tongue = false
}

TFPreset_MoanNormal = {
	updateRate = 0.05,
	mouthSpeed = 3.2,
	faceSpeed = 1.6,
	browSpeed = 2.2,
	auxSpeed = 1.0,
	intensityCurve = 1.4,
	jawBase = -0.2,
	jawWave = 0.12,
	jawPeak = 0.35,
	smileBase = 0.35,
	smileFreq = 0.7,
	smileWave = 0.4,
	smilePeak = 0.25,
	cheekFromSmile = 0.85,
	cheekPeak = 0.35,
	upperLipFreq = 1.1,
	upperLipMax = 0.55,
	upperLipPeak = 0.2,
	lowerLipFreq = 1.5,
	lowerLipMax = 0.45,
	lowerLipPress = 0.2,
	innerJawFreq = 0.6,
	innerJawWave = 0.4,
	innerJawPeak = 0.35,
	browInnerLift = 0.45,
	browInnerPeak = 0.25,
	browOuterFreq = 0.8,
	browOuterPress = 0.25,
	browOuterPeak = 0.2,
	browAsymFreq = 1.1,
	browAsym = 0.15,
	lipPhaseOffset = 0.35,
	tongue = false
}

TFPreset_MoanMedium = {
	updateRate = 0.05,
	mouthSpeed = 1.6,
	faceSpeed = 0.9,
	browSpeed = 1.1,
	auxSpeed = 0.7,
	intensityCurve = 1.1,
	jawBase = -0.25,
	jawWave = 0.25,
	jawPeak = 0.15,
	smileBase = 0.15,
	smileFreq = 0.5,
	smileWave = 0.25,
	smilePeak = 0.15,
	cheekFromSmile = 0.6,
	cheekPeak = 0.15,
	upperLipFreq = 0.7,
	upperLipMax = 0.25,
	upperLipPeak = 0.1,
	lowerLipFreq = 0.8,
	lowerLipMax = 0.25,
	lowerLipPress = 0.1,
	innerJawFreq = 0.45,
	innerJawWave = 0.15,
	innerJawPeak = 0.15,
	browInnerLift = 0.25,
	browInnerPeak = 0.15,
	browOuterFreq = 0.5,
	browOuterPress = 0.15,
	browOuterPeak = 0.1,
	browAsymFreq = 0.6,
	browAsym = 0.08,
	lipPhaseOffset = 0.2,
	tongue = false
}

TFPreset_MoanHigh = {
	updateRate = 0.045,
	mouthSpeed = 4.4,
	faceSpeed = 2.3,
	browSpeed = 3.0,
	auxSpeed = 1.4,
	intensityCurve = 1.8,
	jawBase = -0.35,
	jawWave = 1,
	jawPeak = 0.5,
	smileBase = 0.5,
	smileFreq = 0.9,
	smileWave = 0.55,
	smilePeak = 0.4,
	cheekFromSmile = 1.0,
	cheekPeak = 0.5,
	upperLipFreq = 1.6,
	upperLipMax = 0.75,
	upperLipPeak = 0.35,
	lowerLipFreq = 2.0,
	lowerLipMax = 0.65,
	lowerLipPress = 0.3,
	innerJawFreq = 0.9,
	innerJawWave = 0.55,
	innerJawPeak = 0.5,
	browInnerLift = 0.65,
	browInnerPeak = 0.4,
	browOuterFreq = 1.1,
	browOuterPress = 0.45,
	browOuterPeak = 0.35,
	browAsymFreq = 1.6,
	browAsym = 0.25,
	lipPhaseOffset = 0.45,
	tongue = true
}

TFPreset_MoanMax = {
	updateRate = 0.04,
	mouthSpeed = 6.0,
	faceSpeed = 3.0,
	browSpeed = 4.0,
	auxSpeed = 2.0,
	intensityCurve = 50,
	jawBase = -0.4,
	jawWave = 2,
	jawPeak = 0.6,
	smileBase = 0.6,
	smileFreq = 1.2,
	smileWave = 0.6,
	smilePeak = 0.5,
	cheekFromSmile = 1.2,
	cheekPeak = 0.6,
	upperLipFreq = 2.0,
	upperLipMax = 0.8,
	upperLipPeak = 0.4,
	lowerLipFreq = 2.5,
	lowerLipMax = 0.7,
	lowerLipPress = 0.4,
	innerJawFreq = 1.5,
	innerJawWave = 0.6,
	innerJawPeak = 0.6,
	browInnerLift = 0.8,
	browInnerPeak = 0.5,
	browOuterFreq = 1.5,
	browOuterPress = 0.6,
	browOuterPeak = 0.4,
	browAsymFreq = 2.0,
	browAsym = 0.35,
	lipPhaseOffset = 0.6,
	tongue = true
}